# Generated by Django 5.2.5 on 2025-11-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('therapist', models.CharField(choices=[('cris', 'Cris Adrian Aquino'), ('rodel', 'Rodel Cabanos'), ('rhomar', 'Rhomar Manarang'), ('melson', 'Melson Morta')], max_length=20)),
                ('service', models.CharField(choices=[('swedish', 'Swedish Massage'), ('hotstone', 'Hot Stone Therapy'), ('aroma', 'Aromatherapy'), ('deeptissue', 'Deep Tissue'), ('footspa', 'Foot Spa & Reflexology'), ('couples', 'Couples Retreat')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('addons', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
