# Generated by Django 5.2.5 on 2025-11-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage_app', '0002_booking_notification_seen'),
        ('massage_app', '0003_service_image'),
    ]

    operations = [
    ]
