# Generated by Django 5.2.5 on 2025-11-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage_app', '0005_employee_status'),
        ('massage_app', '0006_employee'),
    ]

    operations = [
    ]
