# Generated by Django 5.2.5 on 2025-11-27 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage_app', '0007_merge_0005_employee_status_0006_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='massage_app.service'),
        ),
    ]
