# Generated by Django 5.2.5 on 2025-12-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage_app', '0010_booking_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='therapist',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
